import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import localFont from 'next/font/local';

// Font files can be colocated inside of `pages`

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={
					'flex min-h-screen flex-col items-center  font-grotesk  pt-0 '
				}
			>
				<Header />
				<div className='mt-5'>{children}</div>
				<Footer />
			</body>
		</html>
	);
}
